#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Editor
export EDITOR='vim'
bindkey -e

# prezto prompt
# autoload -Uz promptinit
# promptinit
# prompt sorin
# zstyle ':prezto:load' pmodule \
#   'git' \
#   'environment' \
#   'terminal' \
#   'editor' \
#   'history' \
#   'directory' \
#   'spectrum' \
#   'utility' \
#   'completion' \
#   'prompt'
# zstyle ':prezto:module:prompt' theme 'sorin'

# peco
function peco-select-history() {
    local tac
    if which tac > /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi
    BUFFER=$(\history -n 1 | \
        eval $tac | \
        peco --query "$LBUFFER")
    CURSOR=$#BUFFER
    zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history

export PATH=/usr/local/bin:$PATH

# rbenv
export PATH="$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init -)"

# aliases
[ -f ~/.zshrc.aliases ] && source ~/.zshrc.aliases

alias be='bundle exec'
alias vfzf='vim $(fzf)'

# activator
export PATH="/usr/local/bin/activator:$PATH"

# scalaenv
export PATH="${HOME}/.scalaenv/bin:${PATH}"
eval "$(scalaenv init -)"

# pyenv
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/shim:$PATH
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init --path)"

# go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH

# android sdk
export ANDROID_SDK_ROOT=/usr/local/share/android
export PATH=${PATH}:${ANDROID_SDK_ROOT}/tools
export PATH=${PATH}:${ANDROID_SDK_ROOT}/platform-tools

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40%'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/shuhei/sdk/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/shuhei/sdk/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/shuhei/sdk/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/shuhei/sdk/google-cloud-sdk/completion.zsh.inc'; fi

# mysql
export PATH=/usr/local/opt/mysql@5.7/bin:$PATH

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/shuhei.nagasawa/.sdkman"
[[ -s "/Users/shuhei.nagasawa/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/shuhei.nagasawa/.sdkman/bin/sdkman-init.sh"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.embulk/bin:$PATH"

# direnv
eval "$(direnv hook zsh)"

# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# adoptopenjdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home/

[[ -s "/Users/shuhei.nagasawa/.gvm/scripts/gvm" ]] && source "/Users/shuhei.nagasawa/.gvm/scripts/gvm"

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# pet
function prev() {
  PREV=$(fc -lrn | head -n 1)
  sh -c "pet new `printf %q "$PREV"`"
}

[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

# starship
eval "$(starship init zsh)"
